# Generated by Django 2.0.5 on 2018-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180518_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('1', 'Chưa đọc'), ('2', 'Đang đọc'), ('3', 'Đã đọc')], max_length=5),
        ),
    ]
